name: Increment Version

on:
  release:
    types: [published]

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Increment version
      uses: jakelee/gh-action-increment-value@v1
      with:
        path: 'version.txt'
        increment: 'patch'

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add version.txt
        git commit -m 'Increment version number'
        git push
